### ISSUE TITLE
Wuggy cannot be installed via pip

### ISSUE THREAD

**Issue by RobinE89** [WuggyCode/wuggy#26]
"Installing Wuggy

Simply run pip install Wuggy and get going! It's never been easier."

ERROR: Could not find a version that satisfies the requirement Wuggy (from versions: none)
ERROR: No matching distribution found for Wuggy
 
pip install Wuggy - is not a part of pipi.org "There were no results for 'wuggy' Did you mean...?"

**Comment by Zenulous** [comment]
Wuggy is now available on pip!
https://pypi.org/project/wuggy/

Enjoy! :)
